### ISSUE TITLE
Meeting todo list

### ISSUE THREAD

**Issue by cwchou2016** [MontyPan/T-Chou#16]
- 為什麼 #14 的 v3 最慢。

**Comment by MontyPan** [comment]
@cwchou2016 要負責的部份：

* [x] 請準備一個 presentation，分析比較 ~~唬爛~~ #15 前後程式碼的差異以及你的心得感想。
    * 再次強調：你不用認同我講的每一句話。很多東西 or 觀念，你現在想反抗反而才是正常。
* [x] 請提出你 2019.02.09（含）以後可以 meeting 的時間
    * 當然如果假期有空，你能肉身來嘉義實際對幹 + 一起吃個飯更好。（本來太座有要回台南娘家，不過後來取消了 QQ）

**Comment by MontyPan** [comment]
結果預期的正規進度幾乎沒進展... :scream:   ~~（我絕對不會怪某人太晚來）~~

請重新提出可以線上 meeting 的時間...... Orz

**Comment by cwchou2016** [comment]
> 請重新提出可以線上 meeting 的時間...... Orz

目前 2/22、23 上午有空。

**Comment by MontyPan** [comment]
那就 02/23 早上十點前，我處理完家務可能會提前摳你
